version: '3.8'

services:
  keycloak-db:
    image: postgres
    volumes:
      - keycloak-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network

  events-finder:
    build:
      context: .
      dockerfile: Dockerfile
    image: events-finder
    ports:
      - "8080:8080"

volumes:
  keycloak-pg:

networks:
  keycloak-network:
    driver: bridge

